name: FreeBetMarket
favicon: null
layout_spectrum: 0.45401
typography_spectrum: 0.14539
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#9a0000'
    - '#8b331d'
    - '#bdb9b9'
    - '#b2786a'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
